import { Navbar } from '@/components/navbar/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Footer } from '@/components/footer/footer'
import { ThemeProvider } from '@/context/ThemeContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true} suppressContentEditableWarning={true}>
      <body className={inter.className} suppressContentEditableWarning={true}>
        <ThemeProvider>
          <div className='container'>
            <div className='wrapper'>
              <Navbar/>
                {children}
              <Footer/>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
